import { expect, test } from '@playwright/test'

test('first setup, lock, unlock and persisted encrypted data', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('textbox').nth(0).fill('correct horse battery staple 2026')
  await page.getByRole('textbox').nth(1).fill('correct horse battery staple 2026')
  await page.getByRole('button', { name: /Create my vault/i }).click()
  await expect(page.getByRole('heading', { name: /Good evening, admin/i })).toBeVisible()
  await page.getByRole('button', { name: /Add password/i }).first().click()
  await page.getByLabel('Website or service').fill('Google Workspace')
  await page.getByLabel('Username or email').fill('admin@example.com')
  await page.getByLabel('Password').fill('Unique-login-password!42')
  await page.getByRole('button', { name: /Save encrypted/i }).click()
  await expect(page.getByText('Changes encrypted and synced.')).toBeVisible()
  await page.getByRole('button', { name: /Lock vault/i }).click()
  await page.getByRole('textbox').first().fill('wrong password')
  await page.getByRole('button', { name: /Unlock vault/i }).click()
  await expect(page.getByText(/Wrong Master Password/i)).toBeVisible()
  await page.getByRole('textbox').first().fill('correct horse battery staple 2026')
  await page.getByRole('button', { name: /Unlock vault/i }).click()
  await expect(page.getByRole('heading', { name: /Good evening, admin/i })).toBeVisible()
  await page.getByRole('button', { name: /All passwords/i }).click()
  await expect(page.getByRole('heading', { name: 'Google Workspace' })).toBeVisible()
})
